Add oscar dummy file to flow generator
Hendrik1704/particle-analysis pull request #23
Opened 2023-06-05 17:10 UTC by NGoetz

This adds dummy file in the oscar format for the flow generator.

2023-06-05 17:58 UTC, Hendrik1704 requested changes

2023-06-05 17:58 UTC, Hendrik1704 commented on src/particle-analysis/GenerateFlow.py
> +            Generate a dummy JETSCAPE file with random particle momenta.
JETSCAPE -> OSCAR

2023-06-05 17:58 UTC, Hendrik1704 commented on src/particle-analysis/GenerateFlow.py
> +                output.write(f"# event {event} end 0 impact  -1.000 scattering_projectile_target no")
There is a tab missing. This should be printed after each event.

2023-06-06 08:03 UTC, NGoetz commented
I fixed the missing tab and change of name.

2023-06-06 08:05 UTC, Hendrik1704 approved these changes
Looks good

2023-06-06 08:05 UTC, merged